# Generated by Django 4.1.7 on 2023-03-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.menu'),
        ),
    ]
