# Generated by Django 4.2.7 on 2023-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_description_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
