# Generated by Django 4.1.7 on 2023-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, null=True, related_name='order_item', to='product.menuitem')),
                ('options', models.ManyToManyField(blank=True, null=True, related_name='order_options', to='product.options')),
            ],
        ),
    ]
