# Generated by Django 4.1.7 on 2023-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0003_remove_order_item_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='product.menuitem'),
        ),
    ]
