# Generated by Django 4.1.7 on 2023-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0005_remove_order_item_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='product.category'),
        ),
    ]
