# Generated by Django 4.1.7 on 2023-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0006_remove_order_category_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_category', to='product.category'),
        ),
    ]
