# Generated by Django 4.1.7 on 2023-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0007_alter_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='options',
        ),
        migrations.AddField(
            model_name='item',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_choice', to='product.choices'),
        ),
    ]
