# Generated by Django 4.1.7 on 2023-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_choices_price'),
        ('orders', '0008_remove_item_options_item_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='product.menuitem'),
        ),
    ]
