# Generated by Django 4.1.7 on 2023-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_category_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items', to='orders.item'),
        ),
    ]
